# Generated by Django 4.2.16 on 2024-11-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facilities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facilityprofile",
            name="open_days",
            field=models.CharField(max_length=100),
        ),
    ]
