# Generated by Django 5.1.2 on 2024-11-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facilities", "0004_inventory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="quantity",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
