# Generated by Django 5.1.2 on 2024-11-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facilities", "0006_alter_inventory_facility_alter_inventory_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="units_received",
            field=models.IntegerField(default=0),
        ),
    ]
