# Generated by Django 5.1.2 on 2024-11-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facilities", "0007_inventory_units_received"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
