# Generated by Django 5.1.2 on 2024-11-14 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facilities", "0008_inventory_updated_at"),
        ("users", "0020_remove_request_status_request_approval_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BloodUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_id", models.CharField(max_length=50, unique=True)),
                (
                    "blood_type",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "donation_type",
                    models.CharField(
                        choices=[
                            ("whole blood", "Whole Blood Donation"),
                            ("plasma", "Plasma Donation"),
                            ("platelets", "Platelet Donation"),
                            ("double red cells", "Double Red Cell Donation"),
                        ],
                        max_length=50,
                    ),
                ),
                ("collection_date", models.DateField()),
                ("expiration_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("issued", "Issued"),
                            ("quarantined", "Quarantined"),
                            ("expired", "Expired"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "donor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bloodunits",
                        to="users.userprofile",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bloodunits",
                        to="facilities.facilityprofile",
                    ),
                ),
            ],
        ),
    ]
