# Generated by Django 4.2.16 on 2024-11-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="address",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="hemoglobin_level",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="is_in_good_health",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="weight",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="firstname",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="lastname",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
