# Generated by Django 4.2.16 on 2024-11-06 17:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_userprofile_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="emergency_contact_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="emergency_contact_phone",
        ),
    ]
