# Generated by Django 4.2.16 on 2024-11-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_userprofile_emergency_contact_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="facility_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="registration_number",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
