# Generated by Django 5.1.2 on 2024-11-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_donationeligibity_eligible"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="approval_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="donation",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="donation",
            name="donation_type",
            field=models.CharField(
                choices=[
                    ("whole_blood", "Whole Blood Donation"),
                    ("plasma", "Plasma Donation"),
                    ("platelets", "Platelet Donation"),
                    ("double red cells", "Double Red Cell Donation"),
                ],
                max_length=50,
            ),
        ),
    ]
