# Generated by Django 5.1.2 on 2024-11-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_donation_approval_date_alter_donation_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="status",
            field=models.CharField(default="scheduled", max_length=50),
        ),
    ]
