# Generated by Django 5.1.2 on 2024-11-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_donation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="is_approved",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
