# Generated by Django 5.1.2 on 2024-11-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_rename_is_approved_donation_approval_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="donation_type",
            field=models.CharField(
                choices=[
                    ("whole blood", "Whole Blood Donation"),
                    ("plasma", "Plasma Donation"),
                    ("platelets", "Platelet Donation"),
                    ("double red cells", "Double Red Cell Donation"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="scheduled",
                max_length=50,
            ),
        ),
    ]
