# Generated by Django 5.1.2 on 2024-11-13 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facilities", "0003_alter_facilityprofile_is_approved"),
        ("users", "0016_alter_request_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests",
                to="facilities.facilityprofile",
            ),
        ),
    ]
