# Generated by Django 5.1.2 on 2024-11-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_alter_request_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="request",
            name="status",
        ),
        migrations.AddField(
            model_name="request",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="request_status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="scheduled",
                max_length=50,
            ),
        ),
    ]
