# Generated by Django 5.1.2 on 2024-11-14 22:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_notifications"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Notifications",
            new_name="Notification",
        ),
    ]
