# Generated by Django 5.1.2 on 2024-11-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0023_remove_notification_message_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="rejection_reason",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
