# Generated by Django 5.1.2 on 2024-11-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0024_donation_rejection_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
