# Generated by Django 5.1.2 on 2024-11-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0025_donation_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="donation_id",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="request",
            name="request_id",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
